[package]
name = "rust-can-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "C FFI bindings for rust-can"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
rust-can-core = { path = "../rust-can-core" }

[lints]
workspace = true
